---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bazzite
    image: ghcr.io/ublue-os/bazzite:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml
verifier:
  name: ansible
